// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeginOperationGroup(arg1) {
  return window['go']['backend']['App']['BeginOperationGroup'](arg1);
}

export function CanRedo() {
  return window['go']['backend']['App']['CanRedo']();
}

export function CanUndo() {
  return window['go']['backend']['App']['CanUndo']();
}

export function CommitOperationGroup() {
  return window['go']['backend']['App']['CommitOperationGroup']();
}

export function CompareFiles(arg1, arg2) {
  return window['go']['backend']['App']['CompareFiles'](arg1, arg2);
}

export function CopyToFile(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CopyToFile'](arg1, arg2, arg3, arg4);
}

export function DiscardAllChanges() {
  return window['go']['backend']['App']['DiscardAllChanges']();
}

export function GetContext() {
  return window['go']['backend']['App']['GetContext']();
}

export function GetInitialFiles() {
  return window['go']['backend']['App']['GetInitialFiles']();
}

export function GetLastOperationDescription() {
  return window['go']['backend']['App']['GetLastOperationDescription']();
}

export function GetLastRedoOperationDescription() {
  return window['go']['backend']['App']['GetLastRedoOperationDescription']();
}

export function GetMinimapVisible() {
  return window['go']['backend']['App']['GetMinimapVisible']();
}

export function GetUnsavedFilesList() {
  return window['go']['backend']['App']['GetUnsavedFilesList']();
}

export function HasUnsavedChanges(arg1) {
  return window['go']['backend']['App']['HasUnsavedChanges'](arg1);
}

export function QuitWithoutSaving() {
  return window['go']['backend']['App']['QuitWithoutSaving']();
}

export function ReadFileContent(arg1) {
  return window['go']['backend']['App']['ReadFileContent'](arg1);
}

export function ReadFileContentWithCache(arg1) {
  return window['go']['backend']['App']['ReadFileContentWithCache'](arg1);
}

export function RedoLastOperation() {
  return window['go']['backend']['App']['RedoLastOperation']();
}

export function RemoveLineFromFile(arg1, arg2) {
  return window['go']['backend']['App']['RemoveLineFromFile'](arg1, arg2);
}

export function RollbackOperationGroup() {
  return window['go']['backend']['App']['RollbackOperationGroup']();
}

export function SaveChanges(arg1) {
  return window['go']['backend']['App']['SaveChanges'](arg1);
}

export function SaveSelectedFilesAndQuit(arg1) {
  return window['go']['backend']['App']['SaveSelectedFilesAndQuit'](arg1);
}

export function SelectFile() {
  return window['go']['backend']['App']['SelectFile']();
}

export function SetCopyLeftMenuItem(arg1) {
  return window['go']['backend']['App']['SetCopyLeftMenuItem'](arg1);
}

export function SetCopyRightMenuItem(arg1) {
  return window['go']['backend']['App']['SetCopyRightMenuItem'](arg1);
}

export function SetDiscardMenuItem(arg1) {
  return window['go']['backend']['App']['SetDiscardMenuItem'](arg1);
}

export function SetFirstDiffMenuItem(arg1) {
  return window['go']['backend']['App']['SetFirstDiffMenuItem'](arg1);
}

export function SetLastDiffMenuItem(arg1) {
  return window['go']['backend']['App']['SetLastDiffMenuItem'](arg1);
}

export function SetMinimapMenuItem(arg1) {
  return window['go']['backend']['App']['SetMinimapMenuItem'](arg1);
}

export function SetMinimapVisible(arg1) {
  return window['go']['backend']['App']['SetMinimapVisible'](arg1);
}

export function SetNextDiffMenuItem(arg1) {
  return window['go']['backend']['App']['SetNextDiffMenuItem'](arg1);
}

export function SetPrevDiffMenuItem(arg1) {
  return window['go']['backend']['App']['SetPrevDiffMenuItem'](arg1);
}

export function SetRedoMenuItem(arg1) {
  return window['go']['backend']['App']['SetRedoMenuItem'](arg1);
}

export function SetSaveAllMenuItem(arg1) {
  return window['go']['backend']['App']['SetSaveAllMenuItem'](arg1);
}

export function SetSaveLeftMenuItem(arg1) {
  return window['go']['backend']['App']['SetSaveLeftMenuItem'](arg1);
}

export function SetSaveRightMenuItem(arg1) {
  return window['go']['backend']['App']['SetSaveRightMenuItem'](arg1);
}

export function SetUndoMenuItem(arg1) {
  return window['go']['backend']['App']['SetUndoMenuItem'](arg1);
}

export function StartFileWatching(arg1, arg2) {
  return window['go']['backend']['App']['StartFileWatching'](arg1, arg2);
}

export function StopFileWatching() {
  return window['go']['backend']['App']['StopFileWatching']();
}

export function UndoLastOperation() {
  return window['go']['backend']['App']['UndoLastOperation']();
}

export function UpdateCopyMenuItems(arg1) {
  return window['go']['backend']['App']['UpdateCopyMenuItems'](arg1);
}

export function UpdateDiffNavigationMenuItems(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateDiffNavigationMenuItems'](arg1, arg2, arg3, arg4);
}

export function UpdateSaveMenuItems(arg1, arg2) {
  return window['go']['backend']['App']['UpdateSaveMenuItems'](arg1, arg2);
}
