// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { main } from "../models";

export function CompareFiles(
	arg1: string,
	arg2: string,
): Promise<main.DiffResult>;

export function CopyLineToFile(
	arg1: string,
	arg2: string,
	arg3: number,
	arg4: string,
): Promise<void>;

export function ReadFileContent(arg1: string): Promise<Array<string>>;

export function ReadFileContentWithCache(arg1: string): Promise<Array<string>>;

export function RemoveLineFromFile(arg1: string, arg2: number): Promise<void>;

export function SaveFile(arg1: string): Promise<void>;

export function SelectFile(): Promise<string>;
