// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CompareFiles(arg1:string,arg2:string):Promise<main.DiffResult>;

export function ReadFileContent(arg1:string):Promise<Array<string>>;

export function SelectFile():Promise<string>;
