// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {menu} from '../models';

export function BeginOperationGroup(arg1:string):Promise<string>;

export function CanUndo():Promise<boolean>;

export function CommitOperationGroup():Promise<void>;

export function CompareFiles(arg1:string,arg2:string):Promise<main.DiffResult>;

export function CopyToFile(arg1:string,arg2:string,arg3:number,arg4:string):Promise<void>;

export function DiscardAllChanges():Promise<void>;

export function GetInitialFiles():Promise<main.InitialFiles>;

export function GetLastOperationDescription():Promise<string>;

export function GetMinimapVisible():Promise<boolean>;

export function GetUnsavedFilesList():Promise<Array<string>>;

export function HasUnsavedChanges(arg1:string):Promise<boolean>;

export function QuitWithoutSaving():Promise<void>;

export function ReadFileContent(arg1:string):Promise<Array<string>>;

export function ReadFileContentWithCache(arg1:string):Promise<Array<string>>;

export function RemoveLineFromFile(arg1:string,arg2:number):Promise<void>;

export function RollbackOperationGroup():Promise<void>;

export function SaveChanges(arg1:string):Promise<void>;

export function SaveSelectedFilesAndQuit(arg1:Array<string>):Promise<void>;

export function SelectFile():Promise<string>;

export function SetCopyLeftMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetCopyRightMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetDiscardMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetFirstDiffMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetLastDiffMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetMinimapMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetMinimapVisible(arg1:boolean):Promise<void>;

export function SetNextDiffMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetPrevDiffMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetSaveAllMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetSaveLeftMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetSaveRightMenuItem(arg1:menu.MenuItem):Promise<void>;

export function SetUndoMenuItem(arg1:menu.MenuItem):Promise<void>;

export function StartFileWatching(arg1:string,arg2:string):Promise<void>;

export function StopFileWatching():Promise<void>;

export function UndoLastOperation():Promise<void>;

export function UpdateCopyMenuItems(arg1:string):Promise<void>;

export function UpdateDiffNavigationMenuItems(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean):Promise<void>;

export function UpdateSaveMenuItems(arg1:boolean,arg2:boolean):Promise<void>;
