name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go-version: ['1.21']
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    
    # Linux specific setup
    - name: Install Linux dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev
    
    # Install Wails
    - name: Install Wails
      run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
    
    # Verify Wails installation
    - name: Wails Doctor
      run: wails doctor
    
    # Backend tests
    - name: Run backend tests
      run: go test ./... -v -cover
    
    # Frontend dependencies
    - name: Install frontend dependencies
      working-directory: frontend
      run: bun install
    
    # Frontend tests
    - name: Run frontend tests
      working-directory: frontend
      run: bun run test:coverage
    
    # Build the application
    - name: Build application
      run: wails build
    
    # Upload artifacts (optional - for debugging)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.os == 'ubuntu-latest' || matrix.os == 'windows-latest'
      with:
        name: weld-${{ matrix.os }}
        path: |
          build/bin/*
        retention-days: 7